# Generated by Django 5.2.6 on 2025-09-14 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedsite',
            old_name='html_code',
            new_name='generated_code',
        ),
        migrations.RenameField(
            model_name='generatedsite',
            old_name='output_file',
            new_name='generated_file',
        ),
        migrations.AlterField(
            model_name='generatedsite',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
