# Generated by Django 5.2.6 on 2025-09-14 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_rename_html_code_generatedsite_generated_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedsite',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='generatedsite',
            name='downloads_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generatedsite',
            name='generation_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedsite',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('websites_generated', models.IntegerField(default=0)),
                ('free_websites_remaining', models.IntegerField(default=2)),
                ('subscription_plan', models.CharField(choices=[('free', 'Free Plan'), ('basic', 'Basic Plan'), ('premium', 'Premium Plan'), ('enterprise', 'Enterprise Plan')], default='free', max_length=20)),
                ('subscription_expires', models.DateTimeField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
